# Generated by Django 5.2.3 on 2025-06-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioActivos',
            fields=[
                ('id_activo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('serie', models.CharField(max_length=255)),
                ('encargado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventarioPiezas',
            fields=[
                ('catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=255)),
                ('inicio_garantia', models.DateField()),
                ('final_garantia', models.DateField()),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tecnico_id', models.IntegerField(blank=True, null=True)),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('estado_trabajo', models.CharField(default='Pendiente', max_length=50)),
            ],
        ),
    ]
